#!/bin/sh

if [ "$DEBUG" = "yes" ]; then
    set -x
fi
set -e

export GITISSUE_VERSION="0.3.4"
export GITISSUE_CACHE_DIR=${GITISSUE_CACHE_DIR:-"$HOME/.gitissue"}
export GITISSUE_CACHE_EXPIRATION=${GITISSUE_CACHE_EXPIRATION:-30}

# The sed expression here replaces all backslashes by forward slashes.
# This helps our Windows users, while not bothering our Unix users.
export GITISSUE_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

usage() {
    cat <<USAGE
usage: git issue <subcommand>

Available subcommands are:
   start    Create a new issue branch & set status to 'In Progress'
   finish   Merge issue branch & set status to 'Resolved'
USAGE
}

main() {
    if [ "$#" -lt 1 ]; then
        usage; exit 1
    fi

    source "$GITISSUE_DIR/gitissue-common"

    local subcommand="$1"; shift
    case $subcommand in
        "-h"|"--help"|"help")
            usage; exit 0
            ;;
        "-v"|"--version")
            subcommand="version"
            ;;
    esac

    if [ ! -e "$GITISSUE_DIR/git-issue-$subcommand" ]; then
        usage; exit 1
    fi
    source "$GITISSUE_DIR/git-issue-$subcommand"

    case $1 in
        "-h"|"--help"|"help")
            subcommand="help"
            ;;
    esac

    if [ ! type "cmd_$subcommand" >/dev/null 2>&1 ]; then
        usage; exit 1
    fi

    cmd_$subcommand "$@"
}

main "$@"
